name: nodejs tb autosign

on: 
  push:
  gollum: 
  schedule: 
      - cron: '0 11,21 * * *'

jobs:
  one:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    # 使用 node:20
    - name: use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    # npm install
    - name: npm install and do sign
      env:
        BDUSS: ${{ secrets.BDUSS }}
      run: |
        npm install
        node index.js

